# Generated by Django 5.2.1 on 2025-05-27 17:38

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0002_film"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="film",
            options={"ordering": [django.db.models.functions.text.Lower("name")]},
        ),
        migrations.CreateModel(
            name="UserFilms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="films.film"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(model_name="film", name="users"),
        migrations.AddField(
            model_name="film",
            name="users",
            field=models.ManyToManyField(
                related_name="films",
                through="films.UserFilms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
